title: sorrynofocus home #title bar in browser
description: > # this means to ignore newlines until "baseurl:"
  You'll find interesting articles, 
  opinions, and trash I've 
  collected on the internets.
permalink: ':title/'

##########################
#uncomment for DEV
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. http://example.com

# uncomment for  PRODUCTION - uncomment
baseurl: "/sorrynofocus.github.io" 
url: "https://github.com/sorrynofocus" 
##########################

sidebar-image: radar.jpg
# background-image: url(http://localhost:4000/assets/img/radar.jpg);

#site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: chris winters # add your name
author-img: cw.jpg # add your photo
#author-img: https://avatars.githubusercontent.com/u/41129889?s=60&v=4 # add your photo
about-author: reflection, reports, & ramblings  # add description
#social-twitter: # add your Twitter handle
#social-facebook: # add your Facebook handle
social-github: sorrynofocus # add your Github handle
social-linkedin: christopherwinters  # add your Linkedin handle
social-email: thechriswinters@gmail.com # add your Email address

# Disqus  - add your discus identifier
#discus-identifier: Gunner 

# Tracker
# Google Analytics
analytics: 

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
